export const queryKeys = {
  content: ["content"] as const,
  settings: ["settings"] as const,
  media: ["media"] as const,
  navbar: ["navbar"] as const,
  hero: ["hero"] as const,
  about: ["about"] as const,
  services: ["services"] as const,
  stack: ["stack"] as const,
  skills: ["skills"] as const,
  experience: ["experience"] as const,
  projects: ["projects"] as const,
  project: (id: string) => ["projects", id] as const,
  blogPosts: ["blog", "posts"] as const,
  blogPost: (id: string) => ["blog", "posts", id] as const,
  blogCategories: ["blog", "categories"] as const,
  footer: ["footer"] as const,
  contact: ["contact"] as const,
  socialLinks: ["social-links"] as const,
  testimonials: ["testimonials"] as const,
  certifications: ["certifications"] as const,
  pricing: ["pricing"] as const,
};
